<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('udhar_conversion', function (Blueprint $table) {
            $table->id();
            $table->unsignedBiginteger('udhar_id');
            $table->enum('custo_type',['s','c'])->comment('s=aupplier,c=customer');
            $table->unsignedBiginteger('custo_id');
            $table->double('curr_from')->comment("The Value of the From at time of conversion");
            $table->double('curr_to')->comment("The Value of the to at time of conversion");
            $table->enum('from',['G','S','M'])->comment("G=Gold,S=Silver,M=Money");
            $table->double('to',['G','S','M'])->comment("G=Gold,S=Silver,M=Money");
            $table->double('from_rate')->comment("Rate of From at time of Conversion");
            $table->double('to_rate')->comment("Rate of To at time of Conversion");
            $table->double('form_quant')->comment("The Quantity of the From that being Converted");
            $table->double('from_value')->comment("The Money Value of From that being Converted");
            $table->double('to_quant')->comment("The Quantity of the To that generated by Conversion");
            $table->unsignedBiginteger('shop_id');
            $table->unsignedBiginteger('branch_id');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('udhar_conversion');
    }
};
